import type { Metadata } from "next";
import { Albert_Sans } from "next/font/google";
import { Stack } from "@mui/material";
import "./globals.css";

const albert_sans = Albert_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ryan Deisler Profile",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={albert_sans.className}>
        <Stack direction={"row"}>
          <h2>Ryan Deisler</h2>
          {children}
        </Stack>
      </body>
    </html>
  );
}
